// screens

export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const TICKETS_SCREEN = 'TICKETS_SCREEN';
export const CONTRIBUTION_SCREEN = 'CONTRIBUTION_SCREEN';
export const MEMBERSHIP_SCREEN = 'MEMBERSHIP_SCREEN';
export const MANAGE_SCREEN = 'MANAGE_SCREEN';

export const AUTH_ROUTES = 'AUTH_ROUTES';