// screens

export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const TICKETS_SCREEN = 'TICKETS_SCREEN';
export const CONTRIBUTION_SCREEN = 'CONTRIBUTION_SCREEN';
export const MEMBERSHIP_SCREEN = 'MEMBERSHIP_SCREEN';
export const MANAGE_SCREEN = 'MANAGE_SCREEN';
export const SHOP_SCREEN = 'SHOP_SCREEN';
export const CART_SCREEN = 'CART_SCREEN';
export const MATCH_STATUS_SCREEN = 'MATCH_STATUS_SCREEN';
export const CONTRIBUTION_SUCCESS_SCREEN = 'CONTRIBUTION_SUCCESS_SCREEN';
export const ORDER_SUCCESS_SCREEN = 'ORDER_SUCCESS_SCREEN';
export const USER_MANAGEMENT_SCREEN = 'USER_MANAGEMENT_SCREEN';
export const USER_ACCOUNT_SCREEN = 'USER_ACCOUNT_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const UPLOAD_SCREEN = 'UPLOAD_SCREEN';
export const TOURNAMENTS_SCREEN = 'TOURNAMENTS_SCREEN';
export const EVENTS_SCREEN = 'EVENTS_SCREEN';


export const AUTH_ROUTES = 'AUTH_ROUTES';
export const USER_PROFILE_ROUTES = 'USER_PROFILE_ROUTES';
