// screens

export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const TICKETS_SCREEN = 'TICKETS_SCREEN';
export const CONTRIBUTION_SCREEN = 'CONTRIBUTION_SCREEN';
export const MEMBERSHIP_SCREEN = 'MEMBERSHIP_SCREEN';
export const MANAGE_SCREEN = 'MANAGE_SCREEN';
export const SHOP_SCREEN = 'SHOP_SCREEN';
export const CART_SCREEN = 'CART_SCREEN';
export const MATCH_STATUS_SCREEN = 'MATCH_STATUS_SCREEN';
export const CONTRIBUTION_SUCCESS_SCREEN = 'CONTRIBUTION_SUCCESS_SCREEN';
export const ORDER_SUCCESS_SCREEN = 'ORDER_SUCCESS_SCREEN';
export const USER_MANAGEMENT_SCREEN = 'USER_MANAGEMENT_SCREEN';
export const USER_ACCOUNT_SCREEN = 'USER_ACCOUNT_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const UPLOAD_SCREEN = 'UPLOAD_SCREEN';
export const TOURNAMENTS_SCREEN = 'TOURNAMENTS_SCREEN';
export const EVENTS_SCREEN = 'EVENTS_SCREEN';
export const EVENT_DETAIL_SCREEN = 'EVENTS_DETAIL_SCREEN';
export const TOURNAMENTS_DETAIL_SCREEN = 'TOURNAMENTS/DETAILSCREEN';
export const VIDEO_STREAM_SCREEN = 'VIDEO_STREAM_SCREEN';
export const OTP_SCREEN = 'OTP_SCREEN';

export const AUTH_ROUTES = 'AUTH_ROUTES';
export const TAB_ROUTES = 'TAB_ROUTES';
export const USER_PROFILE_ROUTES = 'USER_PROFILE_ROUTES';

// common actions
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

// user actions
export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGIN = 'USER_LOGIN';
export const SEND_OTP = 'SEND_OTP';
